### ISSUE TITLE
npm i  error

### ISSUE THREAD

**Issue by jaccen** [0Shark/live-interview#3]
npm error code E401
npm error Incorrect or missing password.
npm error If you were trying to login, change your password, create an
npm error authentication token or enable two-factor authentication then
npm error that means you likely typed your password in incorrectly.
npm error Please try again, or recover your password at:
npm error   https://www.npmjs.com/forgot
npm error
npm error If you were doing some other operation then your saved credentials are
npm error probably out of date. To correct this please try logging in again with:
npm error   npm login

**Comment by 0Shark** [comment]
There is not much information here but I think this is due the the [Font Awesome](https://fontawesome.com/) token missing in the .npmrc file.
```plaintext
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=MY_FONTAWESOME_TOKEN
```

You need to replace ```MY_FONTAWESOME_TOKEN``` with your Font Awesome Pro token from your account to use the Pro icons from their library. If you don't have this you can replace the package with the free version.
